INSERT INTO CATALOGUES("ID", "CODE", "NAME", "TYPE", "URL", "STATUS") VALUES (1, 'cat1', 'Music', 'EXTERNAL', 'http://localhost:8080/external/cat1', 'ACTIVE')
INSERT INTO CATALOGUES("ID", "CODE", "NAME", "TYPE", "URL", "STATUS") VALUES (2, 'cat2', 'Technology', 'EXTERNAL', 'http://localhost:8080/external2/catalogue', 'ACTIVE')
INSERT INTO CATALOGUES("ID", "CODE", "NAME", "TYPE", "URL", "STATUS") VALUES (3, 'cat3', 'Homeware', 'EXTERNAL', 'http://localhost:8080/external3/list', 'ACTIVE')
INSERT INTO CATALOGUES("ID", "CODE", "NAME", "TYPE", "URL", "STATUS") VALUES (4, 'cat4', 'Garden', 'INTERNAL', 'http://localhost:8080/catalogues/cat4', 'ACTIVE')
INSERT INTO CATALOGUES("ID", "CODE", "NAME", "TYPE", "URL", "STATUS") VALUES (5, 'cat5', 'Games', 'INTERNAL', 'http://localhost:8080/catalogues/cat5', 'ACTIVE')
INSERT INTO ITEMS("ID", "PARENT_CODE", "CODE", "NAME", "STATUS") VALUES (1, 'cat4', '10', 'Plant Pot', 'ACTIVE')
INSERT INTO ITEMS("ID", "PARENT_CODE", "CODE", "NAME", "STATUS") VALUES (2, 'cat4', '11', 'Fork', 'ACTIVE')
INSERT INTO ITEMS("ID", "PARENT_CODE", "CODE", "NAME", "STATUS") VALUES (3, 'cat4', '12', 'Lawnmower', 'ACTIVE')
INSERT INTO ITEMS("ID", "PARENT_CODE", "CODE", "NAME", "STATUS") VALUES (4, 'cat5', '13', 'Scrabble', 'ACTIVE')
INSERT INTO ITEMS("ID", "PARENT_CODE", "CODE", "NAME", "STATUS") VALUES (5, 'cat5', '14', 'Cludo', 'ACTIVE')
